---
- name: Wait for API service to come up
  wait_for: host={{kubernetes_overlord.ip}} port=8080

- name: Install kubelet config
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet
  notify: restart minion

- name: Install proxy config
  template: src=proxy.j2 dest=/etc/kubernetes/proxy
  notify: restart minion
