apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-me
    image: mysql
    ports:
    - containerPort: 3006
    env:
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "true"
    volumeMounts:
        # This name must match the volumes.name below.
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    glusterfs:
      endpoints: demo-glusterfs.local
      path: gv0
