apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-me
    image: mysql
    ports:
    - containerPort: 3006
    volumeMounts:
        # This name must match the volumes.name below.
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
volumes:
  - name: mysql-persistent-storage
    gcePersistentDisk:
      # This disk must already exist.
      pdName: mysql-disk
      fsType: ext4
