---
- name: Enable epel-release
  yum: name=epel-release state=installed

- name: Install gluster repo
  yum_repository:
     name: glusterfs-epel
     description: GlusterFS is a clustered file-system capable of scaling to several petabytes.
     baseurl: http://download.gluster.org/pub/gluster/glusterfs/3.7/LATEST/EPEL.repo/epel-$releasever/$basearch/
     skip_if_unavailable: yes
     gpgcheck: yes
     gpgkey: http://download.gluster.org/pub/gluster/glusterfs/3.7/LATEST/rsa.pub

- name: Install gluster noarch repo
  yum_repository:
    name: glusterfs-noarch-epel
    description: GlusterFS is a clustered file-system capable of scaling to several petabytes.
    baseurl: http://download.gluster.org/pub/gluster/glusterfs/3.7/LATEST/EPEL.repo/epel-$releasever/noarch
    skip_if_unavailable: yes
    gpgcheck: yes
    gpgkey: http://download.gluster.org/pub/gluster/glusterfs/3.7/LATEST/rsa.pub

- name: Setup hosts line for gluster
  lineinfile: dest=/etc/hosts line="192.168.23.12 gluster"

- name: Setup hosts line for overlord
  lineinfile: dest=/etc/hosts line="{{kubernetes_overlord.ip}} {{kubernetes_overlord.name}}"

- name: Setup hosts lines for minions
  lineinfile: dest=/etc/hosts line="{{item.ip}} {{item.name}}"
  with_items: "{{kubernetes_minions}}"
