---
- name: Install yum repo
  yum_repository:
    name: virt7-docker-common-release
    description: Kubernetes Repo
    baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
    gpgcheck: no

- name: Install kubernetes and other packages
  yum: name="{{item}}" state="latest"
  with_items:
    - kubernetes
    - glusterfs
    - glusterfs-fuse

- name: Disable host firewall
  service: name=firewalld enabled=no state=stopped


- name: Install kubernetes config
  template: src=config.j2 dest=/etc/kubernetes/config
