---
- name: Install gluster server
  yum: name=glusterfs-server state=latest

- name: Start gluster server
  service: name=glusterd enabled=yes state=started

- name: Make gluster data volume dir
  file: path=/data/brick1/gv0 state=directory recurse=yes

- name: Setup gluster volume
  gluster_volume: state=present name=gv0 brick=/data/brick1/gv0 cluster="gluster"

- name: Start gluster volume
  gluster_volume: state=started name=gv0
