---
- hosts: all
  become: yes
  roles:
    - kubernetes-install
    - flocker-node

- hosts: overlord
  become: yes
  roles:
    - kubernetes-overlord

- hosts: minion
  become: yes
  roles:
    - kubernetes-minion
