---
- hosts: kubernetes
  become: yes
  roles:
    - kubernetes-install

- hosts: overlord
  become: yes
  roles:
    - kubernetes-overlord

- hosts: minion
  become: yes
  roles:
    - kubernetes-minion

- hosts: gluster
  become: yes
  roles:
    - gluster-server
