---
- hosts: all
  become: yes
  roles:
    - base_setup

- hosts: overlord
  become: yes
  roles:
    - kubernetes-install
    - kubernetes-overlord

- hosts: minion
  become: yes
  roles:
    - kubernetes-install
    - kubernetes-minion

- hosts: gluster
  become: yes
  roles:
    - gluster-server
